Transform:
  - AWS::Serverless-2016-10-31
Resources:
  cdkapplambdaroleE7FAD26E:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Statement:
          - Action: sts:AssumeRole
            Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
        Version: '2012-10-17'
      ManagedPolicyArns:
        - Fn::Join:
            - ''
            - - 'arn:'
              - Ref: AWS::Partition
              - :iam::aws:policy/AmazonDynamoDBFullAccess
        - Fn::Join:
            - ''
            - - 'arn:'
              - Ref: AWS::Partition
              - :iam::aws:policy/AWSLambdaFullAccess
      RoleName: cdk-app-lambda-role
      Tags:
        - Key: app
          Value: cdk-app
    Metadata:
      aws:cdk:path: CdkAppStack/cdk-app-lambda-role/Resource
  cdkappfunction1:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: lib/lambda/lambda1
      Handler: index.handler
      Runtime: nodejs12.x
      FunctionName: cdk-app-function-1
      MemorySize: 128
      Role:
        Fn::GetAtt:
          - cdkapplambdaroleE7FAD26E
          - Arn
      Tags:
        app: cdk-app
    Metadata:
      aws:cdk:path: CdkAppStack/cdk-app-function-1
  cdkappsubscription:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: lib/lambda/subscription
      Handler: index.handler
      Runtime: nodejs12.x
      Events:
        subscriptionFilterEventLambda1:
          Properties:
            FilterPattern: '[Error]'
            LogGroupName: /aws/lambda/cdk-app-function-1
          Type: CloudWatchLogs
      FunctionName: cdk-app-subscription
      MemorySize: 128
      Role:
        Fn::GetAtt:
          - cdkapplambdaroleE7FAD26E
          - Arn
      Tags:
        app: cdk-app
    Metadata:
      aws:cdk:path: CdkAppStack/cdk-app-subscription
  cdkappfunction1loggroupA836AF88:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: /aws/lambda/cdk-app-function-1
      RetentionInDays: 365
    UpdateReplacePolicy: Retain
    DeletionPolicy: Retain
    Metadata:
      aws:cdk:path: CdkAppStack/cdk-app-function-1-loggroup/Resource
  cdkappsubscriptionloggroup047D9BE0:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: /aws/lambda/cdk-app-subscription
      RetentionInDays: 365
    UpdateReplacePolicy: Retain
    DeletionPolicy: Retain
    Metadata:
      aws:cdk:path: CdkAppStack/cdk-app-subscription-loggroup/Resource
  CDKMetadata:
    Type: AWS::CDK::Metadata
    Properties:
      Modules: aws-cdk=1.56.0,@aws-cdk/aws-cloudwatch=1.56.0,@aws-cdk/aws-iam=1.56.0,@aws-cdk/aws-logs=1.56.0,@aws-cdk/aws-sam=1.56.0,@aws-cdk/cloud-assembly-schema=1.56.0,@aws-cdk/core=1.56.0,@aws-cdk/cx-api=1.56.0,@aws-cdk/region-info=1.56.0,jsii-runtime=node.js/v12.14.0
    Condition: CDKMetadataAvailable
Conditions:
  CDKMetadataAvailable:
    Fn::Or:
      - Fn::Or:
          - Fn::Equals:
              - Ref: AWS::Region
              - ap-east-1
          - Fn::Equals:
              - Ref: AWS::Region
              - ap-northeast-1
          - Fn::Equals:
              - Ref: AWS::Region
              - ap-northeast-2
          - Fn::Equals:
              - Ref: AWS::Region
              - ap-south-1
          - Fn::Equals:
              - Ref: AWS::Region
              - ap-southeast-1
          - Fn::Equals:
              - Ref: AWS::Region
              - ap-southeast-2
          - Fn::Equals:
              - Ref: AWS::Region
              - ca-central-1
          - Fn::Equals:
              - Ref: AWS::Region
              - cn-north-1
          - Fn::Equals:
              - Ref: AWS::Region
              - cn-northwest-1
          - Fn::Equals:
              - Ref: AWS::Region
              - eu-central-1
      - Fn::Or:
          - Fn::Equals:
              - Ref: AWS::Region
              - eu-north-1
          - Fn::Equals:
              - Ref: AWS::Region
              - eu-west-1
          - Fn::Equals:
              - Ref: AWS::Region
              - eu-west-2
          - Fn::Equals:
              - Ref: AWS::Region
              - eu-west-3
          - Fn::Equals:
              - Ref: AWS::Region
              - me-south-1
          - Fn::Equals:
              - Ref: AWS::Region
              - sa-east-1
          - Fn::Equals:
              - Ref: AWS::Region
              - us-east-1
          - Fn::Equals:
              - Ref: AWS::Region
              - us-east-2
          - Fn::Equals:
              - Ref: AWS::Region
              - us-west-1
          - Fn::Equals:
              - Ref: AWS::Region
              - us-west-2
